### PR TITLE
Fix outdated dependencies

### PR DESCRIPTION
**Pull request by ArjenMiedema**

### CODE REVIEW

**Comment by ArjenMiedema** [comment]
I'm not entirely sure if the dependency on `magento/magento2-base` should stay and if it works. I'll use this branch for now, so let's wait until I'm done updating before we merge and tag this

**Comment by ArjenMiedema** [comment]
I checked all packages in `msp/notifier-all` and created merge requests for all of them. Once these are all merged (including this one) the version in the metapackage might need to be bumped and we can get this to work.

**Comment by giacmir** [comment]
Thank you @ArjenMiedema ,
due to composer behaviour with pre-release versions and the caret sign I suggest to change the dependency marker to `^0` to facilitate upgrades.

**Comment by ArjenMiedema** [comment]
I changed it and did the same to the other packages that needed this change

**Pull request merged**
